Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DownRest.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using Telegram.Bot;
using Telegram.Bot.Args;

namespace DownRest.Controllers
{
    public class ProjectsController : Controller
    {
       
        private UserContext db = new UserContext();
        
        // GET: Projects
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.Cat).Include(p => p.User);
            return View("Index", projects.ToList());
        }

        // GET: Projects/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project != null)
            {
                return PartialView("Details", project);
            }
            return View("Index");
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            Project p = new Project();
            ViewBag.CatId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.UserId = new SelectList(db.Users, "Id", "UserName");
            return PartialView("Create",p);
           // return View(p);
        }

        // POST: Projects/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Description,Reward,CatId")] Project project)
        {
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var store = new UserStore<User>(new UserContext());
                    var userManager = new UserManager<User>(store);
                    User user = userManager.FindByNameAsync(User.Identity.Name).Result;
                    User user2 = db.Users.Find(user.Id);

                    if (user2.balance >= project.Reward)
                    {
                        user2.balance = user2.balance - project.Reward;
                        project.UserId = user.Id;


                        db.Projects.Add(project);
                        db.Entry(user2).State = EntityState.Modified;
                        await db.SaveChangesAsync();

                    return RedirectToAction("Index", "Home", new { area = "" });



                    }
                    else {
                         
                        return RedirectToAction("Profile", "Home", new { error = "Not enough balance" }); }






                   
                }
                else {
                    return new HttpUnauthorizedResult();
                }


            }

            ViewBag.CatId = new SelectList(db.Categories, "Id", "Name", project.CatId);
            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", project.UserId);
            return View(project);
        }
      
        // GET: Projects/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project != null)
            {
                ViewBag.CatId = new SelectList(db.Categories, "Id", "Name", project.CatId);
                ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", project.UserId);
                return PartialView("Edit", project);
            }
           
            return View("Index");
        }

        // POST: Projects/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description,Reward,ClientId,CatId")] Project project)
        {
            ViewBag.CatId = new SelectList(db.Categories, "Id", "Name", project.CatId);
            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", project.UserId);
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project != null)
            {
                 
                return PartialView("Delete", project);
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Project project = await db.Projects.FindAsync(id);
            db.Projects.Remove(project);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DownRest.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace DownRest.Controllers
{
    public class ResponsesController : Controller
    {
        private Context db = new Context();

        // GET: Responses
        public async Task<ActionResult> Index()
        {
            var responses = db.Responses.Include(r => r.User).Include(r => r.Project);
            return View(await responses.ToListAsync());
        }

        // GET: Responses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = await db.Responses.FindAsync(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return View(response);
        }

        // GET: Responses/Create
        public ActionResult Create()
        {
            Response r = new Response();
            ViewBag.FreelancerId = new SelectList(db.Freelancers, "Id", "Name");
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
            return PartialView("Create", r);
        }

        // POST: Responses/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Text")] Response response, int ProjectId)
        {
            var store = new UserStore<User>(new UserContext());
            var userManager = new UserManager<User>(store);
            User user = userManager.FindByNameAsync(User.Identity.Name).Result;

            response.ProjectId = ProjectId;
            response.UserId = user.Id;

            if (ModelState.IsValid)
            {
                db.Responses.Add(response);
                await db.SaveChangesAsync();
                return RedirectToAction("DetailsProject", "Home", new { id = ProjectId });
            }

           
            return View(response);
        }

        // GET: Responses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = await db.Responses.FindAsync(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            ViewBag.FreelancerId = new SelectList(db.Freelancers, "Id", "Name", response.UserId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", response.ProjectId);
            return View(response);
        }

        // POST: Responses/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Text,ProjectId,FreelancerId")] Response response)
        {
            if (ModelState.IsValid)
            {
                db.Entry(response).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.FreelancerId = new SelectList(db.Freelancers, "Id", "Name", response.UserId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", response.ProjectId);
            return View(response);
        }

        // GET: Responses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Response response = await db.Responses.FindAsync(id);
            if (response == null)
            {
                return HttpNotFound();
            }
            return View(response);
        }

        // POST: Responses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Response response = await db.Responses.FindAsync(id);
            db.Responses.Remove(response);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model DownRest.Models.Context
<div class="jumbotron">
    <h1>HELLO WORLD ON ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">

    <a href="/skills">Skills CRUD</a>
    <br>
     
</div>

<div class="row">

    
    <a href="/categories">Categories CRUD</a>
    <br>
</div>

Views/Home/DetailsP.cshtml
@model DownRest.Models.Project



@using DownRest.Models
@{
    ViewBag.Title = "Details";
}
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
 


<script>

    $(function () {
        $("#dialog1").dialog({
            autoOpen: false
        });

        $("#opener").click(function () {
            $("#dialog1").dialog('open');
        });
    });
    $(document).ready(function () {

        $.ajaxSetup({ cache: false });

        $(".viewDialog").on("click", function (e) {
            e.preventDefault();

            $("<div></div>")
                .addClass("dialog")
                .appendTo("body")
                .dialog({
                    title: $(this).attr("data-dialog-title"),
                    close: function () { $(this).remove() },
                    modal: true
                })
                .load(this.href);
        });
    });
</script>
<div>
   

    <div>
        <h4>Project  @Model.Name</h4>
        <div class="card mt-3 " style="

                  ">
            <div class="card-body row">

                <div class="col-3">
                    <img src="~/Files/@Model.User.avatar" width="200" height="200" style="border: 2px green solid">
                </div>

                <div class="col-9">
                    <h5 class="card-title pr-4"> @Model.User.UserName</h5>
                    
                    <h6 class="card-subtitle mb-2 pr-4"> @Model.Description</h6>
                </div>


            </div>
            <div class="card-footer">
                Reward:  @Model.Reward $

            </div>
        
        </div>
        <hr />
        <dl class="dl-horizontal">
           
            <br>
            
             
            <br>
        </dl>
    </div>


    @if (Model.AcceptedBy == 0)  
    {
        @Html.ActionLink("Create Response", "Create", "Responses", new { ProjectId = Model.Id }, new { @class = "viewDialog btn btn-success", data_dialog_title = "Создание модели" })
    }
    @foreach (var item in Model.Responses)
    {



<div class="card mt-3 " style="
                 @if (Model.AcceptedBy == item.Id) {
                     Write("background-color: lightgreen;");
                 }
                  ">
    <div class="card-body row">

        <div class="col-3">
            <img src="~/Files/@item.User.avatar" width="200" height="200" style="border: 2px green solid">
        </div>

        <div class="col-9">
            <h5 class="card-title pr-4">@item.User.UserName</h5>

            <h6 class="card-subtitle mb-2 pr-4">  @item.Text</h6>
        </div>


    </div>
    <div class="card-footer">
        @foreach (Skill sk in item.User.Skills)
        {
           <button class="btn btn-warning mr-2"> @sk.Name </button>
        }

    </div>
    <div class="card-footer">
        @if (User.Identity.Name == Model.User.Email && Model.AcceptedBy == 0)
        {
            @Html.ActionLink("Accept", "AcceptResponse", new { id = item.Id, userId = item.User.Id, projId = Model.Id }, new { @class = "btn btn-success" })
        }

    </div>
</div>






    }



</div>

Views/Home/Index.cshtml
@model IEnumerable<DownRest.Models.Category>
@using DownRest.Models
@{
    ViewBag.Title = "Home Page";
}
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />

@Html.ActionLink("Create New", "Create", "Projects", new { }, new { @class = "viewDialog btn btn-primary my-3", data_dialog_title = "Создание модели" })



<script>

    $(function () {
        $("#dialog1").dialog({
            autoOpen: false
        });

        $("#opener").click(function () {
            $("#dialog1").dialog('open');
        });
    });
    $(document).ready(function () {

        $.ajaxSetup({ cache: false });

        $(".viewDialog").on("click", function (e) {
            e.preventDefault();

            $("<div></div>")
                .addClass("dialog")
                .appendTo("body")
                .dialog({
                    title: $(this).attr("data-dialog-title"),
                    close: function () { $(this).remove() },
                    modal: true
                })
                .load(this.href);
        });
    });
</script>
@foreach (var item in Model)
{


    if (item.Projects.Count > 0)
    {<h3 class="text-center mt-2"><b>Category: @item.Name</b></h3>

    foreach (Project proj in item.Projects)
    {

        if (proj.AcceptedBy == 0)
        {



            <div class="card mt-3 " style="border: 1px solid grey">
                <div class="card-body">
                    <h5 class="card-title">@proj.Name</h5>

                    <h6 class="card-subtitle mb-2 text-muted">by @proj.User.UserName</h6>

                    <a class="btn btn-success" href="/Home/DetailsProject/@proj.Id">Details</a>


                </div>
                <div class="card-footer">
                    Reward: @proj.Reward $ <br>

                </div>
            </div>



            }

        }
    }

}

Views/Home/Profile.cshtml
@using DownRest.Models
@model DownRest.Models.User

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@Model.UserName</h2>

<img src="~/Files/@Model.avatar" width="200" height="200">



<h3>Выберите файл для загрузки</h3>
@using (Html.BeginForm("Upload", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="upload" />
    <br>
    <input type="submit" class="btn btn-success" value="Загрузить" />
}


@using (Html.BeginForm("UpdateProfile", "Home", FormMethod.Post))
{@Html.AntiForgeryToken()

@Html.HiddenFor(model => model.Id)


<br />
if (Request.QueryString["error"] != null)
{
<div class="jumbotron bg-danger p-3 m-3" style="color:white">
    @Request.QueryString["error"]

</div>

}
@Html.LabelFor(model => model.balance, "Balance")
<br />
@Html.Editor("balance") 
<br />
@Html.ValidationMessageFor(model => model.balance, "", new { @class = "text-danger" })



<div class="editor-label"><b>Skills</b></div>
foreach (Skill c in ViewBag.Skills)
{
    <input type="checkbox" name="selectedCourses" value="@c.Id"
           @foreach (Skill b in Model.Skills) { if (c.Id == b.Id) { Write("checked"); break; } } />

    @c.Name
    <br />
}




<input type="submit" class="btn btn-success mt-2" value="Add" />
}
<h3>Accepted responses</h3>
@foreach (Project proj in ViewBag.Projects)
{

    foreach (Response r in ViewBag.Responses)
    {
        if (r.Id == proj.AcceptedBy && r.UserId == Model.Id)
        {


            <div class="card mt-3 " style="border: 1px solid grey">
                <div class="card-body">
                    <h5 class="card-title">@proj.Name</h5>

                    <h6 class="card-subtitle mb-2 text-muted">by @proj.User.UserName</h6>

                    <a class="btn btn-success" href="/Home/DetailsProject/@proj.Id">Details</a>


                </div>
                <div class="card-footer">
                    Reward: @proj.Reward $ <br>

                </div>
            </div>

            break;
        }
    }



}

Views/Home/_ExternalLoginsListPartial.cshtml
@model DownRest.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0)
    {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else
    {
        using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl }))
        {
            @Html.AntiForgeryToken()
            <div class="social-auth-links text-center">
                <p>- OR -</p>
                <p>
                    @foreach (AuthenticationDescription p in loginProviders)
                    {
                        <button type="submit" class="btn btn-block btn-social btn-google btn-flat" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType">
                            <i class="fa fa-google-plus"></i> Sign in using Google+
                        </button>
                    }
                </p>
            </div>
        }
    }
}